FORMAT: 1A
HOST: https://local.api.tankstelle.aral.de

# Aral Station API

The Aral Station API is a modern API that offers information on everything 
related to Aral gas stations. 

<!-- include(introduction/versioning.apib) -->
<!-- include(introduction/json-api.apib) -->
<!-- include(introduction/http-methods.apib) -->
<!-- include(introduction/status-codes.apib) -->

# Group Brands

<!-- include(brands/brands.apib) -->

## Data Structures
<!-- include(errors.mson) -->
<!-- include(brands/brands.mson) -->