# Versioning

The API is currently available in 2 different versions:
- `v1`: legacy endpoint used in older applications.
- `v2`: current, reworked API that should be used in new projects.
`v1` will be supported until usage drops below 2% of API traffic.

This documentation will only cover `v2`. For usage specifications on `v1`
please consult the corresponding documentation.